# -*- coding: utf-8 -*-
"""EV1_H3_CRUZARUQUIPAWILMER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jUGUS1pz0a7Ve6vrYIhGltSj-C-1J2rQ
"""

# ============================================================
# KNN - CLASIFICACIÓN DE CLIENTES
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# ------------------------------------------------------------
# 1. Crear dataset
# ------------------------------------------------------------

data = {
    "edad": [20,22,25,27,30,32,35,38,40,42,45,48,50,55,58],
    "ingreso": [1000,1200,1500,1800,2200,2500,3000,3500,
                4000,4500,5000,5500,6000,7000,8000],
    "compras": [2,3,5,6,8,10,12,15,17,20,23,25,28,30,35],
    "riesgo": [
        "Bajo","Bajo","Bajo","Bajo","Bajo",
        "Medio","Medio","Medio","Medio","Medio",
        "Alto","Alto","Alto","Alto","Alto"
    ]
}

df = pd.DataFrame(data)

df.head()

# ============================================================
# 2. Variables X e y
# ============================================================

X = df[["edad", "ingreso", "compras"]]
y = df["riesgo"]

# División entrenamiento/prueba
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

# Escalamiento
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Crear modelo
knn = KNeighborsClassifier(n_neighbors=3)

# Entrenar
knn.fit(X_train_scaled, y_train)

# Predicción
y_pred = knn.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print()
print(classification_report(y_test, y_pred))

# ============================================================
# 3. Predicción de un NUEVO CLIENTE
# ============================================================

nuevo_cliente = pd.DataFrame({
    "edad": [29],
    "ingreso": [2300],
    "compras": [9]
})

nuevo_cliente_scaled = scaler.transform(nuevo_cliente)

prediccion = knn.predict(nuevo_cliente_scaled)

print("Nuevo cliente:")
print(nuevo_cliente)

print("\nClasificación:", prediccion[0])

# ============================================================
# NAIVE BAYES - DETECTOR DE SPAM
# ============================================================

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report

mensajes = [
    "Gana dinero gratis ahora",
    "Has ganado un premio increíble",
    "Oferta exclusiva gana dinero",
    "Haz clic para recibir tu premio",
    "Dinero gratis disponible hoy",
    "Felicidades eres ganador",
    "Compra ahora y recibe premio",
    "Oferta limitada gana dinero",

    "Hola, nos vemos mañana",
    "Recuerda la reunión de las tres",
    "Te envío el informe solicitado",
    "Puedes revisar el documento",
    "Nos vemos en la universidad",
    "La clase comienza a las ocho",
    "Te mando las fotografías",
    "Mañana terminamos el proyecto"
]

etiquetas = [
    "spam","spam","spam","spam",
    "spam","spam","spam","spam",
    "normal","normal","normal","normal",
    "normal","normal","normal","normal"
]

X_train, X_test, y_train, y_test = train_test_split(
    mensajes,
    etiquetas,
    test_size=0.25,
    random_state=42,
    stratify=etiquetas
)

modelo_spam = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("bayes", MultinomialNB())
])

modelo_spam.fit(X_train, y_train)

predicciones = modelo_spam.predict(X_test)

print("Accuracy:", accuracy_score(y_test, predicciones))
print()
print(classification_report(y_test, predicciones))

# Probar mensajes nuevos

nuevos = [
    "Has ganado dinero gratis",
    "Nos vemos mañana en clase",
    "Oferta exclusiva para ganar dinero",
    "Te envío el informe"
]

predicciones = modelo_spam.predict(nuevos)

for mensaje, pred in zip(nuevos, predicciones):
    print(f"{mensaje} -> {pred}")

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

# Create a pipeline with TfidfVectorizer and RandomForestClassifier
rf_model = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("random_forest", RandomForestClassifier(
        n_estimators=200,
        max_depth=8,
        random_state=42
    ))
])

# Train the model
rf_model.fit(X_train, y_train)

# Make predictions
pred = rf_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

# Importancia de variables para el modelo de detección de spam (Random Forest)
import pandas as pd
import matplotlib.pyplot as plt

# Assuming rf_model from cell GDMD2zuo0Wi- is already trained and available
# Extract the trained RandomForestClassifier and TfidfVectorizer from the pipeline
rf_classifier = rf_model.named_steps['random_forest']
tfidf_vectorizer = rf_model.named_steps['tfidf']

# Get feature names (vocabulary) from the TfidfVectorizer
feature_names = tfidf_vectorizer.get_feature_names_out()

# Get feature importances from the RandomForestClassifier
importances = rf_classifier.feature_importances_

# Create a Pandas Series for better visualization
importancias = pd.Series(importances, index=feature_names)

# Sort the importances and select top N for better readability
top_n = 20
importancias = importancias.sort_values(ascending=False).head(top_n)

print(f"Top {top_n} Importancia de características para el modelo de detección de spam:")
print(importancias)

# Plotting the feature importances
plt.figure(figsize=(12, 6))
importancias.plot(kind="bar")
plt.title(f"Top {top_n} Importancia de características para el modelo de detección de spam")
plt.ylabel("Importancia")
plt.xlabel("Características")
plt.xticks(rotation=90) # Rotate labels for better visibility
plt.tight_layout() # Adjust layout to prevent labels from overlapping
plt.show()

# ============================================================
# IMPORTANCIA DE VARIABLES - RANDOM FOREST
# Dataset Iris
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


# ------------------------------------------------------------
# 1. Cargar dataset
# ------------------------------------------------------------

iris = load_iris()

X = iris.data
y = iris.target


# ------------------------------------------------------------
# 2. Dividir datos en entrenamiento y prueba
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# ------------------------------------------------------------
# 3. Crear modelo Random Forest
# ------------------------------------------------------------

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=8,
    random_state=42
)


# ------------------------------------------------------------
# 4. Entrenar modelo
# ------------------------------------------------------------

rf.fit(X_train, y_train)


# ------------------------------------------------------------
# 5. Realizar predicciones
# ------------------------------------------------------------

pred = rf.predict(X_test)


# ------------------------------------------------------------
# 6. Evaluar modelo
# ------------------------------------------------------------

accuracy = accuracy_score(y_test, pred)

print("Accuracy:", accuracy)


# ------------------------------------------------------------
# 7. Obtener importancia de las variables
# ------------------------------------------------------------

importancias = pd.Series(
    rf.feature_importances_,
    index=iris.feature_names
).sort_values(ascending=False)


print("\nImportancia de características:")
print(importancias)


# ------------------------------------------------------------
# 8. Graficar importancia
# ------------------------------------------------------------

importancias.plot(kind="bar")

plt.title("Importancia de características")
plt.ylabel("Importancia")
plt.xlabel("Características")
plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

svm = Pipeline([
    ("scaler", StandardScaler()),
    ("modelo", SVC(
        kernel="rbf",
        C=2,
        gamma="scale"
    ))
])

svm.fit(X_train, y_train)

pred = svm.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(
    n_estimators=150,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

gb.fit(X_train, y_train)

pred = gb.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

from sklearn.ensemble import AdaBoostClassifier

ada = AdaBoostClassifier(
    n_estimators=100,
    learning_rate=0.5,
    random_state=42
)

ada.fit(X_train, y_train)

pred = ada.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

from lightgbm import LGBMClassifier

lgbm = LGBMClassifier(
    n_estimators=150,
    learning_rate=0.05,
    max_depth=5,
    num_leaves=31,
    random_state=42,
    verbose=-1
)

lgbm.fit(X_train, y_train)

pred = lgbm.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

!pip -q install catboost

from catboost import CatBoostClassifier

cat = CatBoostClassifier(
    iterations=150,
    depth=5,
    learning_rate=0.05,
    verbose=False,
    random_seed=42
)

cat.fit(X_train, y_train)

pred = cat.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

mensajes = [
    "gana dinero gratis",
    "has ganado un premio",
    "oferta exclusiva ahora",
    "haz clic y recibe dinero",
    "premio gratis para ti",
    "ganaste dinero",
    "oferta limitada",
    "recibe tu premio",

    "hola como estas",
    "nos vemos mañana",
    "te envío el informe",
    "recuerda la reunión",
    "la clase comienza temprano",
    "nos vemos en la universidad",
    "puedes revisar el documento",
    "te mando el archivo"
]

y = [
    "spam","spam","spam","spam",
    "spam","spam","spam","spam",
    "normal","normal","normal","normal",
    "normal","normal","normal","normal"
]

X_train, X_test, y_train, y_test = train_test_split(
    mensajes,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

modelo = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("svm", LinearSVC())
])

modelo.fit(X_train, y_train)

pred = modelo.predict(X_test)

print(classification_report(y_test, pred))

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

data = load_breast_cancer()

X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Características:", X.shape[1])
print("Observaciones:", X.shape[0])

from sklearn.neighbors import KNeighborsClassifier

modelo_knn = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier(n_neighbors=7))
])

modelo_knn.fit(X_train, y_train)

pred_knn = modelo_knn.predict(X_test)

print(classification_report(
    y_test,
    pred_knn,
    target_names=data.target_names
))

from sklearn.svm import SVC

modelo_svm = Pipeline([
    ("scaler", StandardScaler()),
    ("svm", SVC(
        kernel="rbf",
        C=2
    ))
])

modelo_svm.fit(X_train, y_train)

pred_svm = modelo_svm.predict(X_test)

print(classification_report(
    y_test,
    pred_svm,
    target_names=data.target_names
))

from sklearn.ensemble import RandomForestClassifier

modelo_rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42
)

modelo_rf.fit(X_train, y_train)

pred_rf = modelo_rf.predict(X_test)

print(classification_report(
    y_test,
    pred_rf,
    target_names=data.target_names
))